// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockElectronica.Data;

#nullable disable

namespace StockElectronica.Migrations
{
    [DbContext(typeof(ProductoContext))]
    [Migration("20230501170638_InicialMigration")]
    partial class InicialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("StockElectronica.Models.NumeroSerie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParNumer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProdId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NumeroSerie");
                });

            modelBuilder.Entity("StockElectronica.Models.Producto", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroSerieId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NumeroSerieId")
                        .IsUnique();

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("StockElectronica.Models.Producto", b =>
                {
                    b.HasOne("StockElectronica.Models.NumeroSerie", "NumeroSerie")
                        .WithOne("producto")
                        .HasForeignKey("StockElectronica.Models.Producto", "NumeroSerieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NumeroSerie");
                });

            modelBuilder.Entity("StockElectronica.Models.NumeroSerie", b =>
                {
                    b.Navigation("producto")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
