// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockElectronica.Data;

#nullable disable

namespace StockElectronica.Migrations
{
    [DbContext(typeof(ProductoContext))]
    partial class ProductoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("MarcaProducto", b =>
                {
                    b.Property<int>("MarcasId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductosId")
                        .HasColumnType("TEXT");

                    b.HasKey("MarcasId", "ProductosId");

                    b.HasIndex("ProductosId");

                    b.ToTable("MarcaProducto");
                });

            modelBuilder.Entity("StockElectronica.Models.Marca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreMarca")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Marca");
                });

            modelBuilder.Entity("StockElectronica.Models.NumeroSerie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParNumer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProdId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NumeroSerie");
                });

            modelBuilder.Entity("StockElectronica.Models.Producto", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroSerieId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NumeroSerieId")
                        .IsUnique();

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("MarcaProducto", b =>
                {
                    b.HasOne("StockElectronica.Models.Marca", null)
                        .WithMany()
                        .HasForeignKey("MarcasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockElectronica.Models.Producto", null)
                        .WithMany()
                        .HasForeignKey("ProductosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StockElectronica.Models.Producto", b =>
                {
                    b.HasOne("StockElectronica.Models.NumeroSerie", "NumeroSerie")
                        .WithOne("producto")
                        .HasForeignKey("StockElectronica.Models.Producto", "NumeroSerieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NumeroSerie");
                });

            modelBuilder.Entity("StockElectronica.Models.NumeroSerie", b =>
                {
                    b.Navigation("producto")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
